name: "✨ Feature Request"
description: "기능 제안 / 개선 요청"
title: "feat: <요약>"
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: "새로운 기능 또는 개선 아이디어를 설명해주세요."
  - type: checkboxes
    id: checklist-search
    attributes:
      label: "사전 확인"
      options:
        - label: "기존 이슈/스펙을 검색했고 중복 제안이 아닙니다."
          required: true
        - label: "해당 기능이 필요한 사용자/페르소나를 파악했습니다."
          required: true
  - type: textarea
    id: user-story
    attributes:
      label: "사용자 스토리"
      description: "누가, 어떤 문제를 해결하려는지 작성"
      placeholder: "As a Teacher, ..."
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: "문제 정의"
      description: "현재의 Pain Point"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: "제안 솔루션"
      description: "핵심 아이디어"
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: "승인 기준"
      description: "AC 3개 이상 bullet로 작성"
      placeholder: "- [ ] ..."
    validations:
      required: true
  - type: textarea
    id: dependency
    attributes:
      label: "의존성 / 참고 자료"
      description: "연관 TODO/PLAN/스펙 링크"
    validations:
      required: false
  - type: textarea
    id: rollout
    attributes:
      label: "롤아웃 고려 사항"
      description: "릴리즈 전략, 위험 요소"
    validations:
      required: false
