/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/teachers/me/assistants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 조교 목록 조회
         * @description 교사가 배정된 조교 목록을 상태별로 확인한다.
         */
        get: operations["getAssistants"];
        put?: never;
        /**
         * 조교 연결
         * @description 검색된 조교를 교사와 연결한다.
         */
        post: operations["assignAssistant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/register/teacher": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 선생님 회원가입
         * @description Teacher 역할 계정을 생성하고 Access/Refresh 토큰을 발급한다.
         */
        post: operations["registerTeacher"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/register/student": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 학생 회원가입
         * @description Student 역할 계정을 생성하고 StudentInfo까지 함께 저장한다.
         */
        post: operations["registerStudent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/register/assistant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 조교 회원가입
         * @description 조교 역할 계정을 생성하고 Access/Refresh 토큰을 발급한다.
         */
        post: operations["registerAssistant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 토큰 재발급
         * @description Refresh 토큰으로 Access 토큰을 재발급한다.
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그아웃
         * @description 갱신 토큰을 만료 처리한다.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그인
         * @description 이메일/비밀번호로 Access/Refresh 토큰을 발급한다.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teachers/me/assistants/{assignmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 조교 활성/비활성화
         * @description 교사가 특정 조교의 접근 권한을 켜거나 끈다.
         */
        patch: operations["updateAssistantStatus"];
        trace?: never;
    };
    "/api/v1/teachers/me/assistants/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 조교 이메일 검색
         * @description 이미 가입한 조교를 이메일로 검색한다.
         */
        get: operations["searchAssistants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 현재 로그인한 사용자 정보 조회
         * @description Access 토큰 기준으로 현재 사용자의 식별자/역할을 조회한다.
         */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AssistantAssignmentCreateRequest: {
            /** Format: uuid */
            assistantMemberId: string;
        };
        AssistantAssignmentResponse: {
            /** Format: uuid */
            assignmentId?: string;
            assistant?: components["schemas"]["AssistantProfile"];
            isActive?: boolean;
            /** Format: date-time */
            assignedAt?: string;
            /** Format: date-time */
            disabledAt?: string;
        };
        AssistantProfile: {
            /** Format: uuid */
            memberId?: string;
            name?: string;
            email?: string;
            phoneNumber?: string;
        };
        RsDataAssistantAssignmentResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["AssistantAssignmentResponse"];
        };
        RegisterMemberRequest: {
            /** Format: email */
            email: string;
            password: string;
            name: string;
            phoneNumber: string;
        };
        LoginResponse: {
            /** Format: uuid */
            memberId?: string;
            accessToken?: string;
            /** Format: date-time */
            accessTokenExpiresAt?: string;
        };
        RsDataLoginResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["LoginResponse"];
        };
        RegisterStudentRequest: {
            /** Format: email */
            email: string;
            password: string;
            name: string;
            phoneNumber: string;
            schoolName: string;
            /** @enum {string} */
            grade: "ELEMENTARY_1" | "ELEMENTARY_2" | "ELEMENTARY_3" | "ELEMENTARY_4" | "ELEMENTARY_5" | "ELEMENTARY_6" | "MIDDLE_1" | "MIDDLE_2" | "MIDDLE_3" | "HIGH_1" | "HIGH_2" | "HIGH_3" | "GAP_YEAR";
            /** Format: date */
            birthDate: string;
            parentPhone: string;
        };
        LogoutRequest: {
            refreshToken?: string;
            logoutAll?: boolean;
        };
        RsDataVoid: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: unknown;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        AssistantAssignmentStatusUpdateRequest: {
            enabled: boolean;
        };
        PageResponseAssistantAssignmentResponse: {
            content?: components["schemas"]["AssistantAssignmentResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
        };
        RsDataPageResponseAssistantAssignmentResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["PageResponseAssistantAssignmentResponse"];
        };
        AssistantSearchResponse: {
            /** Format: uuid */
            assistantMemberId?: string;
            name?: string;
            email?: string;
            phoneNumber?: string;
            /** @enum {string} */
            assignmentStatus?: "NOT_ASSIGNED" | "ACTIVE" | "INACTIVE";
            /** Format: uuid */
            assignmentId?: string;
            /** Format: date-time */
            connectedAt?: string;
            /** Format: date-time */
            disabledAt?: string;
        };
        RsDataListAssistantSearchResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["AssistantSearchResponse"][];
        };
        MeResponse: {
            /** Format: uuid */
            memberId?: string;
            email?: string;
            name?: string;
            /** @enum {string} */
            role?: "TEACHER" | "ASSISTANT" | "STUDENT" | "ADMIN" | "SUPER_ADMIN";
        };
        RsDataMeResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["MeResponse"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAssistants: {
        parameters: {
            query?: {
                status?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataPageResponseAssistantAssignmentResponse"];
                };
            };
        };
    };
    assignAssistant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssistantAssignmentCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataAssistantAssignmentResponse"];
                };
            };
        };
    };
    registerTeacher: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterMemberRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataLoginResponse"];
                };
            };
        };
    };
    registerStudent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterStudentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataLoginResponse"];
                };
            };
        };
    };
    registerAssistant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterMemberRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataLoginResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataLoginResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataLoginResponse"];
                };
            };
        };
    };
    updateAssistantStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignmentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssistantAssignmentStatusUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataAssistantAssignmentResponse"];
                };
            };
        };
    };
    searchAssistants: {
        parameters: {
            query?: {
                email?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataListAssistantSearchResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataMeResponse"];
                };
            };
        };
    };
}
