/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/teachers/me/branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 지점 Assignment 목록
         * @description 선생님이 연결한 지점 목록을 상태별로 조회한다.
         */
        get: operations["getAssignments"];
        put?: never;
        /**
         * 지점 Assignment 생성
         * @description 선생님이 특정 지점과의 연결을 생성한다.
         */
        post: operations["createAssignment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teachers/me/assistants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 조교 목록 조회
         * @description 교사가 배정된 조교 목록을 상태별로 확인한다.
         */
        get: operations["getAssistants"];
        put?: never;
        /**
         * 조교 연결
         * @description 검색된 조교를 교사와 연결한다.
         */
        post: operations["assignAssistant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/register/teacher": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 선생님 회원가입
         * @description Teacher 역할 계정을 생성하고 Access/Refresh 토큰을 발급한다.
         */
        post: operations["registerTeacher"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/register/student": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 학생 회원가입
         * @description Student 역할 계정을 생성하고 StudentInfo까지 함께 저장한다.
         */
        post: operations["registerStudent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/register/assistant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 조교 회원가입
         * @description 조교 역할 계정을 생성하고 Access/Refresh 토큰을 발급한다.
         */
        post: operations["registerAssistant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Teacher 학원 목록 조회
         * @description 교사가 접근 가능한 학원 목록을 상태/타입/키워드로 필터링해 조회한다.
         */
        get: operations["getCompaniesForTeacher"];
        put?: never;
        /**
         * 학원 생성
         * @description Teacher가 INDIVIDUAL 또는 ACADEMY 학원을 등록한다.
         */
        post: operations["createCompany"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 지점 목록 조회
         * @description Teacher 또는 SuperAdmin이 상태/키워드/회사 기준으로 지점을 조회한다.
         */
        get: operations["getBranches"];
        put?: never;
        /**
         * 지점 생성
         * @description Teacher가 기존 학원에 새로운 지점을 추가한다.
         */
        post: operations["createBranch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 토큰 재발급
         * @description Refresh 토큰으로 Access 토큰을 재발급한다.
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그아웃
         * @description 갱신 토큰을 만료 처리한다.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그인
         * @description 이메일/비밀번호로 Access/Refresh 토큰을 발급한다.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teachers/me/branches/{assignmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 지점 Assignment 활성/비활성화
         * @description 선생님이 출강 중단 시 Assignment를 비활성화하고, 필요 시 다시 활성화한다.
         */
        patch: operations["updateAssignmentStatus"];
        trace?: never;
    };
    "/api/v1/teachers/me/assistants/{assignmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 조교 활성/비활성화
         * @description 교사가 특정 조교의 접근 권한을 켜거나 끈다.
         */
        patch: operations["updateAssistantStatus"];
        trace?: never;
    };
    "/api/v1/branches/{branchId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 지점 정보 수정
         * @description 교사(OWNER) 또는 SuperAdmin이 지점 이름/활성 여부를 수정한다.
         */
        patch: operations["updateBranch"];
        trace?: never;
    };
    "/api/v1/branches/{branchId}/verified-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 지점 검증 상태 변경
         * @description SuperAdmin이 지점의 verified 상태 및 활성화를 토글한다.
         */
        patch: operations["updateBranchVerifiedStatus"];
        trace?: never;
    };
    "/api/v1/admin/companies/{companyId}/verified-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 학원 검증 상태 변경
         * @description SuperAdmin이 학원의 검증/활성 상태를 변경한다.
         */
        patch: operations["updateCompanyVerifiedStatus"];
        trace?: never;
    };
    "/api/v1/teachers/me/assistants/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 조교 이메일 검색
         * @description 이미 가입한 조교를 이메일로 검색한다.
         */
        get: operations["searchAssistants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 현재 로그인한 사용자 정보 조회
         * @description Access 토큰 기준으로 현재 사용자의 식별자/역할을 조회한다.
         */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * SuperAdmin 학원 목록 조회
         * @description SuperAdmin이 전체 학원 목록을 검증 상태로 필터링해 조회한다.
         */
        get: operations["getCompaniesForAdmin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/companies/{companyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 학원 상세 조회
         * @description SuperAdmin이 특정 학원 상세 정보를 조회한다.
         */
        get: operations["getCompanyDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BranchInput: {
            /** Format: uuid */
            companyId: string;
            branchName: string;
        };
        CompanyInput: {
            companyName: string;
            branchName: string;
        };
        IndividualInput: {
            companyName: string;
            branchName: string;
        };
        TeacherBranchAssignmentCreateRequest: {
            /** @enum {string} */
            mode: "EXISTING_BRANCH" | "NEW_INDIVIDUAL" | "NEW_COMPANY" | "NEW_BRANCH";
            /** Format: uuid */
            branchId?: string;
            /** @enum {string} */
            role?: "OWNER" | "FREELANCE";
            individual?: components["schemas"]["IndividualInput"];
            company?: components["schemas"]["CompanyInput"];
            branch?: components["schemas"]["BranchInput"];
        };
        RsDataTeacherBranchAssignmentResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["TeacherBranchAssignmentResponse"];
        };
        TeacherBranchAssignmentResponse: {
            /** Format: uuid */
            assignmentId?: string;
            /** Format: uuid */
            branchId?: string;
            branchName?: string;
            /** Format: uuid */
            companyId?: string;
            companyName?: string;
            /** @enum {string} */
            companyType?: "INDIVIDUAL" | "ACADEMY";
            /** @enum {string} */
            verifiedStatus?: "UNVERIFIED" | "VERIFIED";
            /** @enum {string} */
            role?: "OWNER" | "FREELANCE";
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            deletedAt?: string;
        };
        AssistantAssignmentCreateRequest: {
            /** Format: uuid */
            assistantMemberId: string;
        };
        AssistantAssignmentResponse: {
            /** Format: uuid */
            assignmentId?: string;
            assistant?: components["schemas"]["AssistantProfile"];
            isActive?: boolean;
            /** Format: date-time */
            assignedAt?: string;
            /** Format: date-time */
            disabledAt?: string;
        };
        AssistantProfile: {
            /** Format: uuid */
            memberId?: string;
            name?: string;
            email?: string;
            phoneNumber?: string;
        };
        RsDataAssistantAssignmentResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["AssistantAssignmentResponse"];
        };
        RegisterMemberRequest: {
            /** Format: email */
            email: string;
            password: string;
            name: string;
            phoneNumber: string;
        };
        LoginResponse: {
            /** Format: uuid */
            memberId?: string;
            accessToken?: string;
            /** Format: date-time */
            accessTokenExpiresAt?: string;
        };
        RsDataLoginResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["LoginResponse"];
        };
        RegisterStudentRequest: {
            /** Format: email */
            email: string;
            password: string;
            name: string;
            phoneNumber: string;
            schoolName: string;
            /** @enum {string} */
            grade: "ELEMENTARY_1" | "ELEMENTARY_2" | "ELEMENTARY_3" | "ELEMENTARY_4" | "ELEMENTARY_5" | "ELEMENTARY_6" | "MIDDLE_1" | "MIDDLE_2" | "MIDDLE_3" | "HIGH_1" | "HIGH_2" | "HIGH_3" | "GAP_YEAR";
            /** Format: date */
            birthDate: string;
            parentPhone: string;
        };
        CompanyCreateRequest: {
            name: string;
            description?: string;
            /** @enum {string} */
            type: "INDIVIDUAL" | "ACADEMY";
            branchName?: string;
        };
        CompanyResponse: {
            /** Format: uuid */
            companyId?: string;
            name?: string;
            description?: string;
            /** @enum {string} */
            type?: "INDIVIDUAL" | "ACADEMY";
            /** @enum {string} */
            verifiedStatus?: "UNVERIFIED" | "VERIFIED";
            /** Format: uuid */
            creatorMemberId?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            deletedAt?: string;
        };
        RsDataCompanyResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["CompanyResponse"];
        };
        BranchCreateRequest: {
            /** Format: uuid */
            companyId: string;
            name: string;
        };
        BranchResponse: {
            /** Format: uuid */
            branchId?: string;
            /** Format: uuid */
            companyId?: string;
            companyName?: string;
            name?: string;
            /** @enum {string} */
            verifiedStatus?: "UNVERIFIED" | "VERIFIED";
            /** Format: uuid */
            creatorMemberId?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            deletedAt?: string;
        };
        RsDataBranchResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["BranchResponse"];
        };
        LogoutRequest: {
            refreshToken?: string;
            logoutAll?: boolean;
        };
        RsDataVoid: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: unknown;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        TeacherBranchAssignmentStatusUpdateRequest: {
            enabled: boolean;
        };
        AssistantAssignmentStatusUpdateRequest: {
            enabled: boolean;
        };
        BranchUpdateRequest: {
            name?: string;
            enabled?: boolean;
        };
        BranchVerifiedStatusRequest: {
            verified: boolean;
            enabled?: boolean;
        };
        CompanyVerifiedStatusRequest: {
            verified: boolean;
            enabled?: boolean;
        };
        PageResponseTeacherBranchAssignmentResponse: {
            content?: components["schemas"]["TeacherBranchAssignmentResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
        };
        RsDataPageResponseTeacherBranchAssignmentResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["PageResponseTeacherBranchAssignmentResponse"];
        };
        PageResponseAssistantAssignmentResponse: {
            content?: components["schemas"]["AssistantAssignmentResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
        };
        RsDataPageResponseAssistantAssignmentResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["PageResponseAssistantAssignmentResponse"];
        };
        AssistantSearchResponse: {
            /** Format: uuid */
            assistantMemberId?: string;
            name?: string;
            email?: string;
            phoneNumber?: string;
            /** @enum {string} */
            assignmentStatus?: "NOT_ASSIGNED" | "ACTIVE" | "INACTIVE";
            /** Format: uuid */
            assignmentId?: string;
            /** Format: date-time */
            connectedAt?: string;
            /** Format: date-time */
            disabledAt?: string;
        };
        RsDataListAssistantSearchResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["AssistantSearchResponse"][];
        };
        PageResponseCompanyResponse: {
            content?: components["schemas"]["CompanyResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
        };
        RsDataPageResponseCompanyResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["PageResponseCompanyResponse"];
        };
        PageResponseBranchResponse: {
            content?: components["schemas"]["BranchResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
        };
        RsDataPageResponseBranchResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["PageResponseBranchResponse"];
        };
        MeResponse: {
            /** Format: uuid */
            memberId?: string;
            email?: string;
            name?: string;
            /** @enum {string} */
            role?: "TEACHER" | "ASSISTANT" | "STUDENT" | "ADMIN" | "SUPER_ADMIN";
        };
        RsDataMeResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["MeResponse"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAssignments: {
        parameters: {
            query?: {
                status?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataPageResponseTeacherBranchAssignmentResponse"];
                };
            };
        };
    };
    createAssignment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeacherBranchAssignmentCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataTeacherBranchAssignmentResponse"];
                };
            };
        };
    };
    getAssistants: {
        parameters: {
            query?: {
                status?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataPageResponseAssistantAssignmentResponse"];
                };
            };
        };
    };
    assignAssistant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssistantAssignmentCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataAssistantAssignmentResponse"];
                };
            };
        };
    };
    registerTeacher: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterMemberRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataLoginResponse"];
                };
            };
        };
    };
    registerStudent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterStudentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataLoginResponse"];
                };
            };
        };
    };
    registerAssistant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterMemberRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataLoginResponse"];
                };
            };
        };
    };
    getCompaniesForTeacher: {
        parameters: {
            query?: {
                status?: string;
                type?: string;
                keyword?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataPageResponseCompanyResponse"];
                };
            };
        };
    };
    createCompany: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataCompanyResponse"];
                };
            };
        };
    };
    getBranches: {
        parameters: {
            query?: {
                companyId?: string;
                status?: string;
                keyword?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataPageResponseBranchResponse"];
                };
            };
        };
    };
    createBranch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BranchCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataBranchResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataLoginResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataLoginResponse"];
                };
            };
        };
    };
    updateAssignmentStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignmentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeacherBranchAssignmentStatusUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataTeacherBranchAssignmentResponse"];
                };
            };
        };
    };
    updateAssistantStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignmentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssistantAssignmentStatusUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataAssistantAssignmentResponse"];
                };
            };
        };
    };
    updateBranch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                branchId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BranchUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataBranchResponse"];
                };
            };
        };
    };
    updateBranchVerifiedStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                branchId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BranchVerifiedStatusRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataBranchResponse"];
                };
            };
        };
    };
    updateCompanyVerifiedStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                companyId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyVerifiedStatusRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataCompanyResponse"];
                };
            };
        };
    };
    searchAssistants: {
        parameters: {
            query?: {
                email?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataListAssistantSearchResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataMeResponse"];
                };
            };
        };
    };
    getCompaniesForAdmin: {
        parameters: {
            query?: {
                status?: string;
                type?: string;
                keyword?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataPageResponseCompanyResponse"];
                };
            };
        };
    };
    getCompanyDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                companyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataCompanyResponse"];
                };
            };
        };
    };
}
