/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/members/register/teacher": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 선생님 회원가입
         * @description Teacher 역할 계정을 생성하고 Access/Refresh 토큰을 발급한다.
         */
        post: operations["registerTeacher"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/register/student": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 학생 회원가입
         * @description Student 역할 계정을 생성하고 StudentInfo까지 함께 저장한다.
         */
        post: operations["registerStudent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/register/assistant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 조교 초대 기반 회원가입
         * @description 초대 코드로 Assistant 계정을 생성한다.
         */
        post: operations["registerAssistantByInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 조교 초대 생성
         * @description Teacher가 조교를 초대할 수 있는 초대 코드를 발급한다.
         */
        post: operations["createAssistantInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 토큰 재발급
         * @description Refresh 토큰으로 Access 토큰을 재발급한다.
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그아웃
         * @description 갱신 토큰을 만료 처리한다.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그인
         * @description 이메일/비밀번호로 Access/Refresh 토큰을 발급한다.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/invitations/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 초대 코드 검증
         * @description 초대 코드 유효성을 확인한다.
         */
        post: operations["verifyInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/{code}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 조교 초대 취소
         * @description Teacher가 아직 사용되지 않은 초대를 취소한다.
         */
        patch: operations["revokeInvitation"];
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 현재 로그인한 사용자 정보 조회
         * @description Access 토큰 기준으로 현재 사용자의 식별자/역할을 조회한다.
         */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterMemberRequest: {
            /** Format: email */
            email: string;
            password: string;
            name: string;
            phoneNumber: string;
        };
        LoginResponse: {
            /** Format: uuid */
            memberId?: string;
            accessToken?: string;
            /** Format: date-time */
            accessTokenExpiresAt?: string;
        };
        RsDataLoginResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["LoginResponse"];
        };
        RegisterStudentRequest: {
            /** Format: email */
            email: string;
            password: string;
            name: string;
            phoneNumber: string;
            schoolName: string;
            /** @enum {string} */
            grade: "ELEMENTARY_1" | "ELEMENTARY_2" | "ELEMENTARY_3" | "ELEMENTARY_4" | "ELEMENTARY_5" | "ELEMENTARY_6" | "MIDDLE_1" | "MIDDLE_2" | "MIDDLE_3" | "HIGH_1" | "HIGH_2" | "HIGH_3" | "GAP_YEAR";
            /** Format: date */
            birthDate: string;
            parentPhone: string;
        };
        RegisterAssistantByInvitationRequest: {
            /** Format: email */
            email: string;
            password: string;
            name: string;
            phoneNumber: string;
            code: string;
        };
        AssistantInvitationCreateRequest: {
            /** Format: email */
            targetEmail: string;
            /** Format: date-time */
            expiredAt?: string;
        };
        InvitationResponse: {
            code?: string;
            targetEmail?: string;
            /** Format: date-time */
            expiredAt?: string;
        };
        RsDataInvitationResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["InvitationResponse"];
        };
        LogoutRequest: {
            refreshToken?: string;
            logoutAll?: boolean;
        };
        RsDataVoid: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: unknown;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        InvitationVerifyRequest: {
            code: string;
        };
        InvitationVerifyResponse: {
            /** Format: uuid */
            senderId?: string;
            senderName?: string;
            targetEmail?: string;
            /** Format: date-time */
            expiredAt?: string;
        };
        RsDataInvitationVerifyResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["InvitationVerifyResponse"];
        };
        MeResponse: {
            /** Format: uuid */
            memberId?: string;
            email?: string;
            name?: string;
            /** @enum {string} */
            role?: "TEACHER" | "ASSISTANT" | "STUDENT" | "ADMIN" | "SUPER_ADMIN";
        };
        RsDataMeResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["MeResponse"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    registerTeacher: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterMemberRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataLoginResponse"];
                };
            };
        };
    };
    registerStudent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterStudentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataLoginResponse"];
                };
            };
        };
    };
    registerAssistantByInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterAssistantByInvitationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataLoginResponse"];
                };
            };
        };
    };
    createAssistantInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssistantInvitationCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataInvitationResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataLoginResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataLoginResponse"];
                };
            };
        };
    };
    verifyInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitationVerifyRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataInvitationVerifyResponse"];
                };
            };
        };
    };
    revokeInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataMeResponse"];
                };
            };
        };
    };
}
